### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rosettakrb** [nateyolles/aem-developer-chrome#15]
Hi,

This extension no longer works.  when i click the button in the Chrome toolbar, it looks like it's been clicked, but the menu that used to appear doesn't show.

I recently had to uninstall and re-install Chrome, but i also did the same to this plugins.

**Comment by nateyolles** [comment]
Thank for contributing to the project by submitting an issue. I have not experienced this issue nor has it been reported by anyone else. Please keep me updated if this issue persists or if you have any new information to add.

**Comment by nateyolles** [comment]
Unable to reproduce and no further reports in almost 4 months. Closing ticket.
