### ISSUE TITLE
Click on WCMode Edit error

### ISSUE THREAD

**Issue by AxelHo** [nateyolles/aem-developer-chrome#20]
Click on wcmode edit gives the following error
chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/NaN?wcmmode=editundefined
Browser Chrome 44

**Comment by nateyolles** [comment]
Thank you. I will look into this first thing Monday when I return from my trip.

**Comment by nateyolles** [comment]
Are you experiencing this issue in the Chrome Dev channel only? Are you running Chrome Stable as well and do you experience the issue there?

**Comment by AxelHo** [comment]
You are right it is only in Chrome Canary .
It works on Chrome Stable.
So not an issue

**Comment by nateyolles** [comment]
Closing issue. Will watch for the issue in coming releases of Chrome.

**Comment by nateyolles** [comment]
Looks like this became an issue pretty quick as Chrome 43 was released last night. I pushed out the fixed version. Chrome Canary should be working as well.

Thank you!
