### ISSUE TITLE
WCMMODE=disabled no longer works

### ISSUE THREAD

**Issue by peter-razorfish** [nateyolles/aem-developer-chrome#21]
It redirects to chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/NaN?wcmmode=disabledundefined

**Comment by nateyolles** [comment]
Verified the issue. All URL manipulation features were affected such as toggling WCM mode, content finder, classic/touch, debug clientlibs and debug layout. The issue surfaced just as Chrome released their latest version, 43. The issue has been resolved and pushed out to the Google web store.

Chrome will automatically update the plugin or to force it, navigate to chrome://extensions, check "Developer mode" and click "Update extensions now".

**Comment by nateyolles** [comment]
Thank you for the notice Peter.

**Comment by peter-razorfish** [comment]
You're welcome :-)
